### ISSUE TITLE
todeClientImage install fails: faulty filetree package validation logic

### ISSUE THREAD

**Issue by HeSe** [GsDevKit/gsDevKitHome#53]
I just installed a new gsDevKitHome and during install process I get the following error even though all prereques are installed.
ster/repository [00a7df6:master] --- github://GsDevKit/Grease:master/repository
Fetched -> Grease-GemStone300-Core-JohanBrichau.5 --- github://GsDevKit/Grease:master/repository [00a7df6:master] --- github://GsDevKit/Grease:master/repository
Project: Metacello baseline
Project: FileTree baseline
Project: Gofer stable
Fetched -> GemStone-Interactions-dkh.12 --- github://glassdb/glass:master/repository [c27f75c:master] --- github://glassdb/glass:master/repository
...RETRY
...RETRYError: Error while installing tODEa UserDefinedError occurred (error 2318), reason:halt, Class category name 'Core-Squeak' for the class 'SystemOrganizer' is inconsistent with the package name 'Core.v3'
TDTopezGemStoneClient(Object)>>error:
TDTopezGemStoneClient>>installTode:forceGLASSInstall: in Block: [ :ex | self error: 'Error while installing tODE' ...etc...
BlockClosure>>cull:
MethodContext(ContextPart)>>handleSignal: in Block: [ self exceptionHandlerBlock cull: exception ]
BlockClosure>>ensure:

**Comment by dalehenrich** [comment]
@HeSe this looks like a recently introduced error in filetree ... I can see that the filetree package name matching logic is not correct ... I will back out my change ... give me a couple of minutes to back out the filetree change

**Comment by dalehenrich** [comment]
@HeSe I've backed out that particular change, so it might be safe to try again ... I will launch a GsDevKitHome build shortly. You should wait for that to finish successfully, if you want to be sure.

**Comment by dalehenrich** [comment]
[travis tests failed}(https://travis-ci.org/GsDevKit/gsDevKitHome/builds/49028801) ... need to back out more of the changes...

**Comment by dalehenrich** [comment]
@HeSe [build is green](https://travis-ci.org/GsDevKit/gsDevKitHome/builds/49030075), so I've successfully backed out the FileTree changes ... BTW, I made these changes because I realized that when someone does a merge and a package rename is involved, that manual packaging mistakes can be made that can ultimately result in "package corruption" so [I need to add validation to FileTree so that it is not possible to load a package that has been incorrectly specified](https://github.com/dalehenrich/filetree/issues/136) ... the class category and method protocol for extension methods must match the package name, otherwise you have "package corruption" ... the programmatic writer's ensure correctness but human edits cannot be validated until a load is attempted...

I'm closing this bug, now that things are backed out ...

**Comment by HeSe** [comment]
Great! It works again! Thank you @dalehenrich

**Comment by dalehenrich** [comment]
Here's the [final bugfix](https://github.com/dalehenrich/filetree/commit/b224f8b3929bb694fc719530f66b8a52200e32ab)  and a [successful test run](https://travis-ci.org/GsDevKit/GsDevKit/builds/49050938) of a GsDevKit/GsDevKit load using the gemstone2.4_dev branch ... this time, the bugfix for https://github.com/dalehenrich/filetree/issues/136 is ready to rumba
